name: angular-build
on:
  workflow_call:
    inputs:
      aws-s3-bucket-name:
        description: Name of the AWS S3 bucket to deploy to
        required: true
        type: string
      build-output-directory:
        description: Where the build output can be found
        required: false
        type: string
        default: "dist"
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:prod

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ inputs.aws-s3-bucket-name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_APP_DEPLOYER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_APP_DEPLOYER_ACCESS_KEY_SECRET }}
          SOURCE_DIR: ${{ inputs.build-output-directory }}
